server:
  port: 3002

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: lb://productCatalogService
          predicates:
            - Path=/api/v1/**
        - id: user
          uri: lb://userManagementService
          predicates:
            - Path=/api/v1/**