server:
  port: 4000
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: productCatalogService
  datasource:
    url: jdbc:mysql://localhost:3306/product_catalog
    username: root
    password: Andres1201
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true